export const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START';
export const FETCH_PHOTOS_FAILED = 'FETCH_PHOTOS_FAILED';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const CHANGE_ACTIVE_FEATURE = 'CHANGE_ACTIVE_FEATURE';
